# Google Cloud Build configuration for automated deployments
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/dataiku-agent:latest',
      '.'
    ]
  
  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/dataiku-agent:latest']
  
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args: [
      'run', 'deploy', 'dataiku-agent',
      '--image', 'gcr.io/$PROJECT_ID/dataiku-agent:latest',
      '--region', 'us-west1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--memory', '1Gi',
      '--cpu', '2',
      '--max-instances', '10',
      '--min-instances', '1',
      '--concurrency', '1000',
      '--timeout', '900',
      '--port', '8080',
      '--set-env-vars', 'LOG_LEVEL=INFO',
      '--set-secrets', 'SLACK_BOT_TOKEN=slack-bot-token:latest,OPENAI_API_KEY=openai-api-key:latest,BRAVE_API_KEY=brave-api-key:latest'
    ]

# Images to build and push
images:
  - 'gcr.io/$PROJECT_ID/dataiku-agent:latest'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'