# Google Cloud Build configuration for VM deployment
steps:
  # Install dependencies and run tests
  - name: 'python:3.11'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']
    
  - name: 'python:3.11'
    entrypoint: 'python'
    args: ['-m', 'pytest', 'tests/', '-v']
    env:
      - 'PYTHONPATH=/workspace'
    
  # Deploy to VM
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying to VM..."
        gcloud compute ssh dataiku-agent-vm \
          --zone=us-central1-a \
          --ssh-flag="-o StrictHostKeyChecking=no" \
          --command="cd /opt/dataiku/dataiku_agent && sudo -u dataiku /opt/dataiku/deploy.sh"

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: 1200s