# Google Cloud Build configuration for VM deployment
steps:
  # Install dependencies and run tests in single step
  - name: 'python:3.11'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        export PYTHONPATH=/workspace
        python -m pytest tests/ -v
    
  # Deploy to VM
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Deploying to VM..."
        gcloud compute ssh dataiku-agent-vm \
          --zone=us-central1-a \
          --ssh-flag="-o StrictHostKeyChecking=no" \
          --command="cd /opt/dataiku/dataiku_agent && sudo -u dataiku bash scripts/deploy.sh"

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: 1200s